Repository GDG-ZIMEET/ZIMEET-BackEnd, pull requests merged in 2025-03, with the labels that each got.

#92 Refactor: 하이 관련 코드 리팩토링
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
Labels: ♻️ REFACTOR

#90 [feat] 카카오 페이 결제 기능 구현 및 동시성 제어
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/order/client/KaKaoPayApiClient.java
  src/main/java/com/gdg/z_meet/domain/order/controller/KaKaoPayController.java
  src/main/java/com/gdg/z_meet/domain/order/controller/OrderVerifyController.java
  src/main/java/com/gdg/z_meet/domain/order/converter/KaKaoPayApproveConverter.java
  src/main/java/com/gdg/z_meet/domain/order/converter/KaKaoPayReadyConverter.java
  src/main/java/com/gdg/z_meet/domain/order/dto/KaKaoPayApproveDTO.java
  src/main/java/com/gdg/z_meet/domain/order/dto/KaKaoPayReadyDTO.java
  src/main/java/com/gdg/z_meet/domain/order/dto/SaveAmountRequest.java
  src/main/java/com/gdg/z_meet/domain/order/entity/ItemPurchase.java
  src/main/java/com/gdg/z_meet/domain/order/entity/KaKaoPayData.java
  src/main/java/com/gdg/z_meet/domain/order/entity/Orders.java
  src/main/java/com/gdg/z_meet/domain/order/entity/ProductType.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPaymentMethod.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPaymentStatus.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPayments.java
  src/main/java/com/gdg/z_meet/domain/order/repository/ItemPurchaseRepository.java
  src/main/java/com/gdg/z_meet/domain/order/repository/KaKaoPayDataRepository.java
  src/main/java/com/gdg/z_meet/domain/order/repository/NamedLockRepository.java
  src/main/java/com/gdg/z_meet/domain/order/service/KaKaoPayService.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/java/com/gdg/z_meet/global/security/UserId.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ FEAT

#93 [chore] 운영 DB 마이그레이션
  src/main/resources/db/migration/V6__Update_Set.sql
Labels: 🥡 CHORE

#95 [feat] 랜덤 미팅 구현
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/MatchingMessageSubscriber.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/RandomConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/RandomResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Matching.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/UserMatching.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/MatchingStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/TeamType.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/Verification.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/MatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserMatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/global/config/RedisConfig.java
  src/main/java/com/gdg/z_meet/global/config/RedisMatchingConfig.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/config/WebSocketConfig.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/jwt/StompAuthInterceptor.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#96 [refactor] user 기능 리팩토링
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/exception/BusinessException.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtValidationException.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ♻️ REFACTOR

#98 [feat] 랜덤 미팅 조회
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
Labels: ✨ FEAT

#101 [#100] Fix: 채팅방 내 사용자 조회시 상대방 이름이 나오는 오류수정
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
Labels: 🐛 FIX

#102 [refactor] 팀 상세조회 시 하이 보낸 여부 반환
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: ♻️ REFACTOR, ✨ FEAT

#105 [#104] Fix: 사용자 조회시 닉네임이 조회되도록 설정
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
Labels: 🐛 FIX

#106 [fix] 미팅 로직의 학과 반환 수정
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: 🐛 FIX

#109 #108 [feat] 로그인 상태확인 api 구현
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
Labels: ✨ FEAT

#110 #108 [refactor] 컨트롤러 빌드 -> dto에서 생성으로
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
Labels: ♻️ REFACTOR

#111 [chore] 운영 DB 마이그레이션
  src/main/resources/db/migration/V7__Update_Set.sql
Labels: 🥡 CHORE

#112 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/MatchingMessageSubscriber.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/RandomConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/RandomResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Matching.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/UserMatching.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/MatchingStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/TeamType.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/Verification.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/MatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserMatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/RedisConfig.java
  src/main/java/com/gdg/z_meet/global/config/RedisMatchingConfig.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/config/WebSocketConfig.java
  src/main/java/com/gdg/z_meet/global/exception/BusinessException.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtValidationException.java
  src/main/java/com/gdg/z_meet/global/jwt/StompAuthInterceptor.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/db/migration/V7__Update_Set.sql
Labels: 🥡 CHORE

#113 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/global/config/WebSocketConfig.java
Labels: 🥡 CHORE

#114 [fix] cookie 설정 변경
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
Labels: 🐛 FIX

#115 [fix] 쿠키 객체 생성X
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
Labels: 🐛 FIX

#118 [chore] Nginx 웹 서버 로드밸런싱 적용
  .github/workflows/gdg-ci-cd.yml
  docker-compose.yml
  nginx/nginx.conf
Labels: 🥡 CHORE

#116 [refactor] 회원가입, 로그인 필터X, userDetails 캐시추가
  src/main/java/com/gdg/z_meet/domain/user/service/UserDetailsService.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR

#117 [fix] 팀원 추가 로직 수정
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: 🐛 FIX

#120 [chore] 운영 DB 마이그레이션
  src/main/java/com/gdg/z_meet/HealthCheckController.java
  src/main/resources/db/migration/V8__Update_Set.sql
Labels: 🥡 CHORE

#121 [chore] 운영 서버 최신화
  .github/workflows/gdg-ci-cd.yml
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/gdg/z_meet/HealthCheckController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserDetailsService.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V8__Update_Set.sql
Labels: 🥡 CHORE

#123 [feat] 리프레시 토큰 DB에 저장
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/repository/RefreshTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
Labels: ✨ FEAT

#127 [feat] 유저정보 중복여부 조회
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#129 [feat] 팀 상태 컬럼 추가
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/ActiveStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/order/service/KaKaoPayService.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#132 [Refactor] 하이 삭제 구현
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
Labels: ♻️ REFACTOR

#133 [feat] 행사 정보 추가
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/Event.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#134 [chore] 운영 DB 마이그레이션 (Ver.9)
  src/main/resources/db/migration/V9__Update_Set.sql
Labels: 🥡 CHORE

#135 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/ActiveStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/Event.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/order/service/KaKaoPayService.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/db/migration/V9__Update_Set.sql
Labels: 🥡 CHORE

#137 [feat] 팀 삭제 기회 부스용
  src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
Labels: ✨ FEAT

#139 [fix] 부스 등록 api 수정
  src/main/java/com/gdg/z_meet/domain/booth/controller/BoothController.java
  src/main/java/com/gdg/z_meet/domain/booth/converter/BoothConverter.java
  src/main/java/com/gdg/z_meet/domain/booth/dto/BoothRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Place.java
  src/main/java/com/gdg/z_meet/domain/booth/service/BoothCommandService.java
  src/main/java/com/gdg/z_meet/domain/booth/service/BoothCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java
Labels: 🐛 FIX

#140 [chore] DB 마이그레이션
  nginx/nginx.conf
  src/main/resources/db/migration/V10__Update_Set.sql
Labels: 🥡 CHORE

#141 [chore] 운영 서버 최신화
  nginx/nginx.conf
  src/main/java/com/gdg/z_meet/domain/booth/controller/BoothController.java
  src/main/java/com/gdg/z_meet/domain/booth/converter/BoothConverter.java
  src/main/java/com/gdg/z_meet/domain/booth/dto/BoothRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Place.java
  src/main/java/com/gdg/z_meet/domain/booth/service/BoothCommandService.java
  src/main/java/com/gdg/z_meet/domain/booth/service/BoothCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/resources/db/migration/V10__Update_Set.sql
Labels: 🥡 CHORE

#145 [refactor] 토큰 검증 과정 리팩토링
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
Labels: ♻️ REFACTOR

#143 [fix] 부스 등록 api JWT필터 수정
  src/main/java/com/gdg/z_meet/domain/booth/dto/BoothRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Item.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
Labels: 🐛 FIX

#146 [chore] 운영 DB 마이그레이션 (Ver.11)
  src/main/resources/db/migration/V11__Update_Set.sql
Labels: 🥡 CHORE

#147 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/booth/dto/BoothRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Item.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/resources/db/migration/V11__Update_Set.sql
Labels: 🥡 CHORE

#149 [feat] ZI밋+ 등급 등록 부스용
  src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
Labels: ✨ FEAT

#150 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
Labels: 🥡 CHORE

#153 [chore] 운영 서버 최신화
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
Labels: 🥡 CHORE

#155 [fix] 팀원 조회 로직 수정
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: 🐛 FIX

#156 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: 🥡 CHORE

#158 [refactor] hard delete -> soft delete로 변경
  src/main/java/com/gdg/z_meet/domain/order/repository/ItemPurchaseRepository.java
  src/main/java/com/gdg/z_meet/domain/user/entity/Terms.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserTerms.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserDetailsService.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ♻️ REFACTOR

#160 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/order/repository/ItemPurchaseRepository.java
  src/main/java/com/gdg/z_meet/domain/user/entity/Terms.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserTerms.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserDetailsService.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: 🥡 CHORE

#162 [chore] 운영 DB 마이그레이션 (Ver.12)
  src/main/resources/db/migration/V12__Update_Set.sql
Labels: 🥡 CHORE

#163 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/Verification.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/resources/db/migration/V12__Update_Set.sql
Labels: 🥡 CHORE

#164 [feat] 팀 인증 부스용
  src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: ✨ FEAT

#165 [chore] 운영 서버 최신화
  build.gradle
  src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/config/RedisConfig.java
Labels: 🥡 CHORE

#167 [fix] soft delete에 따른 레포지토리 수정
  src/main/java/com/gdg/z_meet/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: 🐛 FIX

#161 [#159] Fix: 회원 탈퇴시 채팅방 나가기 처리
  src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: 🐛 FIX

#169 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: 🥡 CHORE

#170 [fix] 랜덤미팅 현황 조회 에러 해결
  src/main/java/com/gdg/z_meet/domain/meeting/repository/MatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
Labels: 🐛 FIX

#172 [fix] 지밋플러스 조회 에러
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: 🐛 FIX

#175 [fix] userMatching 삭제 안 되는 에러 해결
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserMatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
Labels: 🐛 FIX

#176 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserMatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
Labels: 🥡 CHORE
