Repository GDG-ZIMEET/ZIMEET-BackEnd, pull requests merged in 2025-01, with the labels that each got.

#6 [feat] 엔티티 클래스 작성
  src/main/java/com/gdg/z_meet/Application.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Category.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Item.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/ChatRoom.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/JoinChat.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/Message.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/TeamType.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/UserTeam.java
  src/main/java/com/gdg/z_meet/domain/order/entity/Order.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPayments.java
  src/main/java/com/gdg/z_meet/domain/user/entity/Terms.java
  src/main/java/com/gdg/z_meet/domain/user/entity/Token.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserTerms.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Emoji.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Gender.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Grade.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/IdealAge.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/IdealType.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/MBTI.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Music.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Style.java
  src/main/java/com/gdg/z_meet/global/common/BaseEntity.java
  src/main/java/com/gdg/z_meet/global/common/Notification.java
Labels: ✨ FEAT

#7 [feat] Toss Payments 주문 정보 검증 기능 구현
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/order/controller/OrderVerifyController.java
  src/main/java/com/gdg/z_meet/domain/order/dto/SaveAmountRequest.java
  src/main/java/com/gdg/z_meet/domain/order/entity/Order.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPaymentMethod.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPaymentStatus.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPayments.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Emoji.java
  src/main/java/com/gdg/z_meet/global/common/Notification.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/java/com/gdg/z_meet/global/response/Response.java
Labels: ✨ FEAT

#14 [feat] 회원가입 시 유저 상세정보 받기
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: ✨ FEAT

#17 [chore] docker 구축 및 배포 환경 세팅
  Dockerfile
  build.gradle
  docker-compse.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🥡 CHORE

#18 [feat] 부스배치도 구현
  src/main/java/com/gdg/z_meet/domain/booth/controller/ClubController.java
  src/main/java/com/gdg/z_meet/domain/booth/converter/ClubConverter.java
  src/main/java/com/gdg/z_meet/domain/booth/dto/ClubRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/booth/dto/ClubResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Place.java
  src/main/java/com/gdg/z_meet/domain/booth/repository/ClubRepository.java
  src/main/java/com/gdg/z_meet/domain/booth/service/ClubCommandService.java
  src/main/java/com/gdg/z_meet/domain/booth/service/ClubCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/booth/service/ClubQueryService.java
  src/main/java/com/gdg/z_meet/domain/booth/service/ClubQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#22 [chore] 운영 서버 DB Flyway 마이그레이션 적용
  build.gradle
  src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Item.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/ChatRoom.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/JoinChat.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/Message.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/UserTeam.java
  src/main/java/com/gdg/z_meet/domain/order/entity/Orders.java
  src/main/java/com/gdg/z_meet/domain/order/entity/TossPayments.java
  src/main/java/com/gdg/z_meet/domain/user/entity/RefreshToken.java
  src/main/java/com/gdg/z_meet/domain/user/entity/Terms.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserTerms.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__Initial_Set.sql
Labels: 📝 DOCS, 🥡 CHORE

#24 [CI/CD] CI/CD 파이프라인 구축
  .github/workflows/gdg-ci-cd.yml
Labels: 🥡 CHORE, :baby_chick: CI/CD
