Repository GDG-ZIMEET/ZIMEET-BackEnd, pull requests merged in 2025-02, with the labels that each got.

#26 [feat] 미팅 팀 소개 구현
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Verification.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/global/common/AuthenticatedUserUtils.java
  src/main/java/com/gdg/z_meet/global/config/SwaggerConfig.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#34 [fix] 부스배치도 계좌 반환
  src/main/java/com/gdg/z_meet/domain/booth/converter/BoothConverter.java
  src/main/java/com/gdg/z_meet/domain/booth/dto/BoothResponseDTO.java
Labels: 🐛 FIX

#37 [fix] CORS 수정 및 URL 추가
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
Labels: 🐛 FIX

#39 [ chore] 운영 환경 DB 마이그레이션 (Ver.2)
  src/main/resources/db/migration/V2__Update_Set.sql
Labels: 🥡 CHORE

#42 [chore] main 최신화
  .github/workflows/gdg-ci-cd.yml
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🥡 CHORE

#43 [feat] 미팅 팀 갤러리 구현
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
Labels: ✨ FEAT

#46 [feat] 우리팀 소개 구현
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
Labels: ✨ FEAT

#50 [feat] 팀명 중복확인 기능 구현
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: ✨ FEAT

#53 [refactor] 팀 전공, 음악 중복처리
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: ♻️ REFACTOR

#57 [chore] main 최신화 전 DB 마이그레이션
  src/main/resources/db/migration/V3__Update_Set.sql
Labels: 📝 DOCS, 🥡 CHORE

#48 [chore] Nginx 웹 서버 구축, Reverse Proxy 및 https 적용
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/gdg/z_meet/EnvTest.java
  src/main/java/com/gdg/z_meet/HealthCheckController.java
  src/main/java/com/gdg/z_meet/StaticController.java
  src/main/java/com/gdg/z_meet/domain/booth/controller/BoothController.java
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/order/controller/OrderVerifyController.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/config/SwaggerConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
Labels: 📝 DOCS, 🥡 CHORE

#59 [feat] 팀 만들기 구현
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#60 [chore] 운영 서버 최신화
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/gdg/z_meet/EnvTest.java
  src/main/java/com/gdg/z_meet/HealthCheckController.java
  src/main/java/com/gdg/z_meet/StaticController.java
  src/main/java/com/gdg/z_meet/domain/booth/controller/BoothController.java
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/order/controller/OrderVerifyController.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/config/SwaggerConfig.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
Labels: 🥡 CHORE, 🏗️ BUILD

#61 [feat] 프로필 조회, 수정 기능
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: ✨ FEAT

#65 [Refactor] 회원가입 시 전화번호 받기
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: ♻️ REFACTOR

#66 [feat] 미팅 팀 삭제
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#68 [feat] 팀원 검색
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#62 [feat] 하이 관련 기능
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/status/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ♻️ REFACTOR, ✨ FEAT

#71 랜덤미팅 남은 티켓 개수 조회하는 로직 구현
  .gitignore
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/RandomConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/RandomResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
Labels: ✨ FEAT

#73 [chore] DB 마이그레이션
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V4__Update_Set.sql
Labels: 🥡 CHORE, 🏗️ BUILD

#75 [chore] 운영 서버 최신화
  .gitignore
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/RandomConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/RandomResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/status/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V4__Update_Set.sql
Labels: 🥡 CHORE

#78 [refactor] 프로필 조회시 userid, gender 같이 반환, 로그인 시 userid 반환
  src/main/java/com/gdg/z_meet/domain/user/dto/Token.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/RefreshToken.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/repository/RefreshTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
Labels: ♻️ REFACTOR

#82 [chore] 운영 DB 마이그레이션
  src/main/resources/db/migration/V5__Update_Set.sql
Labels: 🥡 CHORE

#83 [chore] 운영 서버 최신화
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/status/HiStatus.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/Token.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/RefreshToken.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/repository/RefreshTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/resources/db/migration/V5__Update_Set.sql
Labels: 🥡 CHORE

#85 [feat] user 리팩토링, 로그아웃, 회원탈퇴 기능 구현
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/RefreshToken.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/repository/RefreshTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/java/com/gdg/z_meet/global/jwt/StompAuthInterceptor.java
Labels: ♻️ REFACTOR, ✨ FEAT

#84 [FEAT, REFACTOR] 채팅 관련 기능 구현 및 리팩토링
  build.gradle
  src/main/java/com/gdg/z_meet/Application.java
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/gdg/z_meet/domain/chat/dto/ChatMessage.java
  src/main/java/com/gdg/z_meet/domain/chat/dto/ChatRoomDto.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/ChatRoom.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/JoinChat.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/Message.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/status/ChatType.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/status/JoinChatStatus.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/MessageRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/mongo/MongoMessageRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageQueryService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageService.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/config/JpaConfig.java
  src/main/java/com/gdg/z_meet/global/config/MongoConfig.java
  src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR, ✨ FEAT

#89 [Fix] #88: 하이 조회시 상대방 팀과 내 팀 ID를 조회할 수 있도록 수정
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
Labels: 🐛 FIX
