Repository GDG-ZIMEET/ZIMEET-BackEnd, pull requests merged in 2025-05, with the labels that each got.

#183 [FEAT, REFACTOR] 하이,채팅 1:1 추가 및 코드 리팩토링
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/chat/dto/ChatRoomDto.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/ChatRoom.java
  src/main/java/com/gdg/z_meet/domain/chat/entity/status/ChatType.java
  src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiType.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: 🐛 FIX, ♻️ REFACTOR, ✨ FEAT

#185 [FEAT] 비밀번호 찾기 구현
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#186 [FEAT] Controller 사용자 인증 처리 로직 커스터마이징
  .gitignore
  build.gradle
  src/main/java/com/gdg/z_meet/global/config/WebConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/AuthUserArgumentResolver.java
  src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
  src/main/java/com/gdg/z_meet/global/security/AuthUser.java
Labels: ✨ FEAT

#188 [FEAT][TEST] FCM 토큰 관리 및 관련 기능 단위 테스트
  build.gradle
  src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/test/java/com/gdg/z_meet/service/FcmServiceImplTest.java
Labels: ✨ FEAT, 📔 TEST

#189 [REFACTOR] FCM 토큰 전달 방식 쿼리 파라미터 -> 커스텀 헤더로 변경
  src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
  src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
Labels: ♻️ REFACTOR

#190 [FEAT] 1대1 미팅 구현
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: ✨ FEAT

#193 [CHORE] DB Migration Ver.14
  src/main/resources/db/migration/V14__Update_Set.sql
Labels: 📝 DOCS, 🥡 CHORE

#195 [FEAT] 1:1 & 2:2 매칭 및 미팅 관련 FCM 알림 구현
  build.gradle
  src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
  src/main/java/com/gdg/z_meet/domain/fcm/feign/FcmFeignClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/feign/FcmFeignConfig.java
  src/main/java/com/gdg/z_meet/domain/fcm/feign/FcmFeignRes.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmChatMessageService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmMeetingMessageService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepositoryCustom.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepositoryImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/global/config/QueryDslConfig.java
  src/test/java/com/gdg/z_meet/service/FcmServiceImplTest.java
Labels: ✨ FEAT

#194 [FEAT] 1대1 미팅 참여
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/entity/enums/ProfileStatus.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#199 [FEAT] 1대1 미팅 내 프로필 조회
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: ✨ FEAT

#201 [FEAT] FCM 1:1 & 2:2 프로필 조회 수 관련 알림 구현
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmMeetingMessageService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmProfileMessageService.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
Labels: ✨ FEAT

#202 [FEAT] 나의 남은 하이 개수
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
Labels: ✨ FEAT

#204 [CHORE] DB Migration (Ver.14 추가본)
  src/main/resources/db/migration/V14__Update_Set.sql
Labels: 🥡 CHORE

#207 [CI/CD] CI 워크플로우 수정 및 로깅 추가
  .github/workflows/gdg-ci-cd.yml
Labels: 🏗️ BUILD, :baby_chick: CI/CD

#209 [FEAT] FCM 전체공지용 알림 기능 구현
  .gitignore
  src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmBroadcastReq.java
  src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
Labels: ✨ FEAT

#210 [CI/CD][CHORE] Deploy to Production Server
  .github/workflows/gdg-ci-cd.yml
  .gitignore
  src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmBroadcastReq.java
  src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
Labels: 🥡 CHORE, :baby_chick: CI/CD

#213 [CHORE] DB Migration Ver.15
  src/main/java/com/gdg/z_meet/domain/fcm/entity/FcmToken.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/resources/db/migration/V15__Update_Set.sql
Labels: 🥡 CHORE

#215 [CI/CD][CHORE] Deploy to Production Server
  src/main/java/com/gdg/z_meet/HealthCheckController.java
  src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
  src/main/java/com/gdg/z_meet/domain/fcm/entity/FcmToken.java
  src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/User.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/db/migration/V15__Update_Set.sql
Labels: 🥡 CHORE, :baby_chick: CI/CD

#219 [QA][REFACTOR] QA 전 리팩토링
  .github/workflows/gdg-ci-cd.yml
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmChatMessageService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmMeetingMessageService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmProfileMessageService.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepositoryImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR, :imp: QA

#224 [FIX] 미팅 리팩토링
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: 🐛 FIX

#226 [FEAT] 1대1 상세조회
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: ✨ FEAT

#227 [QA][REFACTOR] FCM 채팅 관련 알림 리팩토링 및 QA
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmChatMessageService.java
Labels: ♻️ REFACTOR, :imp: QA

#229 [CI/CD][CHORE] Deploy to Production Server
  .github/workflows/gdg-ci-cd.yml
  src/main/java/com/gdg/z_meet/domain/booth/entity/Category.java
  src/main/java/com/gdg/z_meet/domain/booth/entity/Place.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmChatMessageService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmMeetingMessageService.java
  src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmProfileMessageService.java
  src/main/java/com/gdg/z_meet/domain/meeting/MatchingMessageSubscriber.java
  src/main/java/com/gdg/z_meet/domain/meeting/RandomScheduler.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/converter/RandomConverter.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/dto/RandomResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/Matching.java
  src/main/java/com/gdg/z_meet/domain/meeting/entity/MatchingQueue.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepositoryImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/MatchingQueueRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/MatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserMatchingRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
  src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
  src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
  src/main/java/com/gdg/z_meet/global/config/RedisConfig.java
  src/main/java/com/gdg/z_meet/global/jwt/StompAuthInterceptor.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V16__Update_Set.sql
Labels: 🥡 CHORE, :baby_chick: CI/CD

#231 [FIX] 역직렬화 오류로 인한 ObjectMapper 설정 수정
  src/main/java/com/gdg/z_meet/global/config/RedisConfig.java
Labels: 🐛 FIX

#232 [CI/CD][CHORE] Deploy to Production Server
  src/main/java/com/gdg/z_meet/global/config/RedisConfig.java
Labels: 🥡 CHORE, :baby_chick: CI/CD

#234 [REFACTOR] 행사 정보 아우름제로 변경
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: ♻️ REFACTOR

#235 [CI/CD][CHORE] Deploy to Production Server
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
  src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: 🥡 CHORE, :baby_chick: CI/CD

#237 [FIX] 미팅에 행사 정보 반영
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: 🐛 FIX

#238 [CI/CD][CHORE] Deploy to Production Server
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: 🥡 CHORE, :baby_chick: CI/CD

#240 [FEAT] 부스용 결제
  src/main/java/com/gdg/z_meet/domain/event/Product.java
  src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/event/dto/EventResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: ✨ FEAT

#242 [QA][FIX] 서비스 운영 중 발생한 오류 해결
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageQueryService.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmSendReq.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
Labels: 🐛 FIX, ♻️ REFACTOR, :imp: QA

#243 [CI/CD][CHORE] Deploy to Production Server
  src/main/java/com/gdg/z_meet/domain/chat/controller/ChatWebSocketController.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
  src/main/java/com/gdg/z_meet/domain/chat/service/MessageQueryService.java
  src/main/java/com/gdg/z_meet/domain/event/Product.java
  src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java
  src/main/java/com/gdg/z_meet/domain/event/dto/EventResponseDTO.java
  src/main/java/com/gdg/z_meet/domain/event/service/EventService.java
  src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmSendReq.java
  src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
  src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
Labels: ♻️ REFACTOR, :baby_chick: CI/CD

#245 [FIX] 받은 하이 프로필 에러
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
Labels: 🐛 FIX

#247 [CI/CD][CHORE] Deploy to Production Server
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandServiceImpl.java
  src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
  src/main/java/com/gdg/z_meet/global/response/Code.java
Labels: :baby_chick: CI/CD, :imp: QA

#251 [FIX] 하이 리스트에서 다른 유저 데이터 조회
  src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
  src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
Labels: 🐛 FIX
